apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "chromadb.fullname" . }}
  labels:
    app: {{ include "chromadb.name" . }}
spec:
  replicas: {{ .Values.replicaCount }}
  selector:
    matchLabels:
      app: {{ include "chromadb.name" . }}
  template:
    metadata:
      labels:
        app: {{ include "chromadb.name" . }}
    spec:
      containers:
        - name: chromadb
          image: "{{ .Values.image.repository }}:{{ .Values.image.tag }}"
          imagePullPolicy: {{ .Values.image.pullPolicy | default "IfNotPresent" }}
          ports:
            - containerPort: 8000
          volumeMounts:
            - name: chroma-data
              mountPath: /chroma
          resources:
            {{- toYaml .Values.resources | nindent 12 }}
      volumes:
        - name: chroma-data
          persistentVolumeClaim:
            claimName: {{ include "chromadb.fullname" . }}-pvc
