apiVersion: v1
kind: Service
metadata:
  name: {{ include "neo4j.fullname" . }}
spec:
  clusterIP: None
  selector:
    app: {{ include "neo4j.name" . }}
  ports:
    - name: http
      port: 7474
      targetPort: 7474
    - name: bolt
      port: 7687
      targetPort: 7687
