replicaCount: 1

image:
  repository: ghcr.io/chroma-core/chroma
  tag: latest
  pullPolicy: IfNotPresent

persistence:
  enabled: true
  size: 10Gi
  storageClass: standard

service:
  type: ClusterIP
  port: 8000

resources:
  requests:
    cpu: 250m
    memory: 512Mi
  limits:
    cpu: 500m
    memory: 1Gi
#The volume is mounted at /chroma, which is the default working directory for ChromaDB.