image:
  repository: yourrepo/rag-api
  tag: latest
  pullPolicy: IfNotPresent

env:
  CHROMA_HOST: chromadb
  NEO4J_URI: bolt://neo4j:7687
  NEO4J_USER: neo4j
  NEO4J_PASS: neo4jpassword

service:
  type: ClusterIP
  port: 8080

resources:
  requests:
    cpu: 100m
    memory: 128Mi
  limits:
    cpu: 500m
    memory: 512Mi